# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Kindle Screensaver
version: 0.0.5
slug: kindle-screensaver
description: The addon creates regularly takes a screenshot which can be polled and used as a Kindle screensaver image of the online screensaver plugin.
startup: application
boot: auto
arch:
  - aarch64
  - amd64
  - armv7
url: 'https://github.com/cosenary/hass-kindle-screensaver'
image: 'ghcr.io/cosenary/hass-kindle-screensaver-{arch}'
webui: 'http://[HOST]:[PORT:3000]'
ingress: true
ingress_port: 3000
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: 'Webserver hosting rendered screensaver image'
map:
  - media:rw
watchdog: 'http://[HOST]:[PORT:3000]/'
init: false
options:
  DEPARTURE_STATION: ''
  DEPARTURE_DESTINATION_STATIONS: []
  DEPARTURE_DESTINATION_CATEGORIES: []
  DEPARTURE_CONNECTION_LIMIT: '10'
  RENDERING_SCREEN_HEIGHT: '800'
  RENDERING_SCREEN_WIDTH: '600'
  ADDITIONAL_ENV_VARS: []
schema:
  DEPARTURE_STATION: "str?"
  DEPARTURE_DESTINATION_STATIONS:
    - "str?"
  DEPARTURE_DESTINATION_CATEGORIES:
    - line: "str?"
      category: "str"
  DEPARTURE_CONNECTION_LIMIT: "int?"
  RENDERING_SCREEN_HEIGHT: "int?"
  RENDERING_SCREEN_WIDTH: "int?"
  ADDITIONAL_ENV_VARS:
    - name: match(^[A-Z0-9_]+$)
      value: str
environment:
  output_path: "/output/cover"
