name: ci

on: workflow_dispatch
  #push:
  #  tags: [ 'v*.*.*' ]

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract package version
        run: node -p -e '`PACKAGE_VERSION=${require("./app/package.json").version}`' >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push HA_Addon AMD64 to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/amd64-base:latest
          platforms: linux/amd64
          push: true
          tags: |
            metz/hass-kindle-screensaver:${{ env.PACKAGE_VERSION }}-amd64,
            metz/hass-kindle-screensaver:latest-amd64
      - name: Build and push HA_Addon aarch64 to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/aarch64-base:latest
          platforms: linux/arm64/v8
          push: true
          tags: |
            metz/hass-kindle-screensaver:${{ env.PACKAGE_VERSION }}-aarch64,
            metz/hass-kindle-screensaver:latest-aarch64
      - name: Build and push HA_Addon ARMv7 to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/armv7-base:latest
          platforms: linux/arm/v7
          push: true
          tags: |
            metz/hass-kindle-screensaver:${{ env.PACKAGE_VERSION }}-armv7,
            metz/hass-kindle-screensaver:latest-armv7
