name: ci

on:
  push:
    #tags: [ 'v*.*.*' ]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.addon }} ${{ matrix.arch }} add-on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - amd64
          - armv7
          - aarch64

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.0

      - name: Extract package version
        run: node -p -e '`PACKAGE_VERSION=${require("./app/package.json").version}`' >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Building multi-platform images under emulation with QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/${{ matrix.platform }}-base:latest
          platforms: linux/${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/hass-kindle-screensaver-${{ matrix.platform }}:${{ env.PACKAGE_VERSION }}
            ghcr.io/${{ github.repository_owner }}/hass-kindle-screensaver-${{ matrix.platform }}:latest
